#!/bin/bash

clear
echo Scanning for new Packages...
rm Packages
./dpkg-scanpackages Files /dev/null > Packages
read -p "Press Enter to Continue"

echo Creatng new Package file...
rm Packages.gz
rm Packages.bz2
gzip -c9 Packages > Packages.gz
bzip2 -c9 Packages > Packages.bz2